# Generated by Django 4.1.5 on 2023-01-26 16:21
# this is what django determines what should be sent to sql database

from django.db import migrations, models

# Migration a subclass of migrations.Migration
class Migration(migrations.Migration):

    # setting this to true inticates that this is an initial migration created when starting a new Django project
    initial = True

    # does not depend on other migrations to be executed
    dependencies = [
    ]

    # the actual migration operation - single operation which creates a new table in database
    operations = [
        migrations.CreateModel(

            # will create a new table named "Artist" in the database with the specified fields and options
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=500)),
                ('verified_artist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={

                # specifies that the rows in the table shoudl be ordered by name
                'ordering': ['name'],
            },
        ),
    ]
