# Generated by Django 4.1.5 on 2023-01-27 02:35

# important to handle foreign key deletions
from django.db import migrations, models
import django.db.models.deletion

# Migration a subclass of migrations.Migration
class Migration(migrations.Migration):

    # requires previous migration
    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [

        # create a new model in database called Song
        migrations.CreateModel(

            name='Song',

            # fields created in Song model
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('length', models.IntegerField(default=0)),

                # references the Artist model from main database
                # ForeignKey() specifies that if associated artist is deleted, so will the song
                # related_name attribute sets the reverse relation from the "Artist" model to the "Song" model, allowing access to the songs of an artist
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main_app.artist')),
            ],
        ),
    ]
